### ISSUE TITLE
Scaling machine-types? Scaling postgres and django independently?

### ISSUE THREAD

**Issue by dcgoss** [waprin/kubernetes_django_postgres_redis#1]
Hey, thanks for the great content in your tutorial!
I have two questions about scaling the postgres and django pods/services created.

First, I understand that we can resize/autoscale the number of nodes in the cluster, however it seems to me that we are limited to using the machine type that we specified when we created the cluster. 

How does one deal with resizing the machine-type of the cluster? I've seen http://stackoverflow.com/questions/31302233/resize-instance-types-on-container-engine-cluster
but it seems the only way to upgrade the machine type is to copy&modify the instance group and restart the cluster, which causes downtime. Furthermore, if you were to update the cluster with `gcloud container clusters upgrade CLUSTER_NAME` your machine-type would roll back to the original type.
How does one deal with these limitations? Could you create another cluster and failover?

Second, it seems that your django pods and your postgres pods will eventually need different levels of node performance. The django pods are pretty stateless and can be horizontally scaled, but the postgres pod will eventually need to run on a bigger instance than the django pods. Does one have to create two separate clusters for the django and postgres, and then scale each independently?

Thanks in advance,
Derek

**Comment by waprin** [comment]
@dcgoss Sorry I missed this and didn't answer it sooner.

To change the instance type, you don't need downtime as long as you keep one instance. You can change the instance type of your managed instance group template and then start killing the old nodes. The managed instance group will replace them with instances of the new type and Container Engine can reschedule the Pods. 

I haven't observed the cluster upgrade reverting the instance type after you changed it. Have you tested this? If so, sounds like a bug.

As far as Django and Postgres, in the Pod definitions you can specify resource constraints:

https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/compute-resources.md

I agree you would want a bigger Node for Postgres. The managed instance groups will add nodes of the given type from the template, I think you could mess around changing the template and replacing nodes until you had the composition you want. I feel like there's probably a way to manually add a node to a cluster but I haven't done it yet, I could look into it if you'd like.

Tthe real problem is just that Postgres has so much state in one Pod. What you really want is a scalable Postgres solution with high availability and failover. I am going to work on that soon, I am publishing part 2 of the Medium series that will walk through most of the rest of this README this week, then in the next few months will work on a more resilient setup for both the Redis and the Postgres parts of the stack.

**Comment by waprin** [comment]
The more I think about it, the more I think you raise a very good point, so I am going to follow up further with the GKE team about getting heterogenous clusters as a feature.

**Comment by dcgoss** [comment]
Sorry for the delayed response - I guess we're equal! 
The killing off the nodes one by one is a great idea, albeit a workaround. I haven't tested that behavior myself with the upgrading, although I did read that it happened [here](http://stackoverflow.com/a/31303169/3194789).
It looks to me like the GKE team might be a step ahead of you. The [gcloud release notes](https://cloud.google.com/sdk/release_notes) list: 

> Added node pool support to enable heterogeneous clusters (alpha).

**Comment by dcgoss** [comment]
I think you can manually add a node to a cluster by "cloning" a node in the Cloud console. You can change the instance type when you clone it, so this is ond workaround for heterogeneous clusters. 

Also, Kubernetes allows for [assigning pods for specific nodes](http://kubernetes.io/docs/user-guide/node-selection/).

**Comment by waprin** [comment]
Yes, good catch on the release notes, looks like GKE team is ahead of me. I was aware you could assign a Pod to a Node but I wasn't aware of the clone trick. Thanks for answering your own question and some great feedback! You are definitely ahead of the curve on this stuff.

**Comment by thesandlord** [comment]
Yup, I can confirm that cloning an instance and changing it does work. But it is overly complicated, because you have to create the instance using the command line (the container image is not on the GUI), which means copy and pasting HUGE startup scripts. 

The better way, as @waprin told me, is to create a new instance template with a different machine type, and switch the Instance Group to use the new template. Then scale the group up.

**Comment by waprin** [comment]
Checking out Terraform is still on my to-do list :)
