### ISSUE TITLE
Project <project_name> is not fully initialized with the default service accounts.

### ISSUE THREAD

**Issue by duebbert** [waprin/kubernetes_django_postgres_redis#2]
Trying to follow the tutorial from a completely clean account (and not much experience with gcloud so far), I get the above error when I try to create the cluster with ```gcloud container clusters create guestbook --scopes "https://www.googleapis.com/auth/userinfo.email","cloud-platform" --num-nodes 2```

Just used ```gcloud container clusters create guestbook``` instead. 

Maybe some instructions missing? I still don't know what exactly the error means.

**Comment by waprin** [comment]
@duebbert it takes a few minutes for a new project to spin up fully and be ready to create a container engine cluster. If you just waited a minute the error would go away, which is why your second command worked.

The scopes are necessary if you want to be able to access Google APIs from your cluster. Compute Engine instances (which container engine runs on top of) have their own service accounts which can be used to auth to APIs. Once the instance is created, you can't change the scope, so your instances can't use most Cloud APIs. The workaround if you end up needing those APIs is to either rebuild the cluster, or create a new Service Account, download it as a JSON key, upload that JSON to your cluster (probably as a Kubernetes secret) and then auth using that by pointing GOOGLE_APPLICATION_CREDENTIALS to it.

The other thing you removed was --num-nodes 2. The default is 3, I was trying to create a smaller cluster to save some people checking it out some money.

All of this may be irrelevant because this project doesn't demonstrate any Google APIs, but hopefully that explains the error and the purpose of the arguments.

**Comment by duebbert** [comment]
@waprin  Thanks for the explanation, Bill. I'm pretty sure I got stuck on this step for at least 45-60 minutes trying out different combinations and creating API keys etc because I thought that was the problem (googling showed nothing for the specific error). Anyway, appreciate it's not really an issue with your tutorial but might be worth mentioning in the text that it might take a while.

**Comment by waprin** [comment]
Yes I will update the README. It took you 60 minutes though? It shouldn't have been longer then a minute or two.

**Comment by duebbert** [comment]
Doing the tutorial again and found the problem. After creating the project I had to go to https://console.cloud.google.com/kubernetes/list so that the container engine gets initialised. After that the creating the cluster with the scopes worked without issues... I've forked the project and will do edits to the readme to reflect what my experience is in setting this all up. Will do a pull request once finished.

**Comment by waprin** [comment]
Sounds good to me.

**Comment by rasekar2000** [comment]
ERROR: (gcloud.container.clusters.create) ResponseError: code=503, message=Project -------------------- is not fully initialized with the default service accounts. Please try again later. 
When I am getting the same, I recreated the API Manager API Key. Then it helped me to create the cluster. Thanks
