### ISSUE TITLE
Missing Files?

### ISSUE THREAD

**Issue by pjmayhew** [waprin/kubernetes_django_postgres_redis#9]
I am interested in the Minikube implementation but the reference to minikube files seems to be missing? In the README you ref:

kubectl apply -f kubernetes_configs/postgres/postgres_minikube.yaml
kubectl apply -f kubernetes_config/guestbook/guestbook_minikube.yaml

But they're not there!? :-)

**Comment by waprin** [comment]
@pjmayhew first of all, very sorry for delay in response here, I was traveling when you created the issue then lost track of it when I got back.

The idea behind those two files is that they are both generated from Jinja templates. Since they share a lot of the same configuration it's helpful to use one file as the base template which you should see in there. So you have to install Jinja cli and run it to generate it, filing in the appropriate .json files( `gke_jinja.json` and `minikube_jinja.json`) with variables relevant to your specific setup. 

Then do:

    pip install -r requirements-dev.txt # install Jinja CLI
    make templates # runs Jinja to create templates ,see MAKEFILE for more detail

Going to make a PR to try to clarify this a bit.

Thanks for the feedback, let me know if yo have any more problems, if I don't respond in a a few days feel free to ping me again.

**Comment by waprin** [comment]
@pjmayhew closing for now, feel free to re-open or open a new issue if you have any more questions.
